stages:
  - build-tests
  
deployingLibrary:
  image: node:20-alpine
  stage: build-tests
  artifacts: 
    paths:
      - coverage
  script:
    - npm i
    - npm run build
    - npm run test
    - cp package.json dist/package.json
    - cd dist
    - npm config set -- "@uniride:registry=https://gitlab.com/api/v4/projects/51670335/packages/npm/"
    - npm config set -- "//gitlab.com/api/v4/projects/51670335/packages/npm/:_authToken" "${NPM_TOKEN}"
    - npm config set -- "//gitlab.com/api/v4/projects/51670335/packages/npm/:_authToken" "${NPM_TOKEN}"
    - npm config set -- "//gitlab.com/api/v4/packages/npm/:_authToken" "${NPM_TOKEN}"
    - npm publish
  only:
    - main